# for https://mybinder.org
# from https://github.com/binder-examples/python-conda_pip/blob/master/environment.yml
name: openrouteservice-examples
channels:
  - conda-forge
dependencies:
  - python
  - folium
  - pandas
  - shapely
  - fiona
  - requests
  - geopandas
  - seaborn
  - rasterio
  - rasterstats
  - mapclassify
  - pip:
      - openrouteservice
      - ortools
      - jupytext
      - pyproj
